environment:
  rabbitmq_download_url: https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.2/rabbitmq-server-3.5.2.exe
  rabbitmq_installer_path: C:\Users\appveyor\rabbitmq.exe

cache:
- "%rabbitmq_installer_path%"
  
install:
- echo Downloading Rabbit...
- ps: |
    $webclient = New-Object System.Net.WebClient
    if (-Not (Test-Path "$env:rabbitmq_installer_path")) {
      $webclient.DownloadFile("$env:rabbitmq_download_url", "$env:rabbitmq_installer_path")
    } else {
      Write-Host "Found" $env:rabbitmq_installer_path "in cache."
    }
- echo Installing Rabbit...
- start /B /WAIT %rabbitmq_installer_path% /S
- ps: (Get-Service -Name RabbitMQ).Status

version: 2.0.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  verbosity: normal
test: on
after_test:
- ps: dotnet pack .\Orleans.Streams.RabbitMqStreamProvider\Orleans.Streams.RabbitMqStreamProvider.csproj --configuration "Release;Platform=AnyCPU" --output ..\artifacts /p:Version=${env:APPVEYOR_BUILD_VERSION}
artifacts:
- path: .\artifacts\*.nupkg
  name: Puhlish NuGets
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: H4JCQw+sdgjjdzvYzjUSW4Kgp8RV1TN17tDSUMJ00OHQvQ4mf0qpaBg0Sl6eyrZ2
  skip_symbols: true
  artifact: /.*\.nupkg/